version: "3.8"
services:
  backend:
    build: ./backend
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./:/backend
      - backend_deps:/backend/node_modules

volumes:
  backend_deps: {}
